"""Add setup models for home/company modes

Revision ID: 4a9972c08188
Revises: c4e2f5d8a1b2
Create Date: 2026-04-10 00:52:38.693161
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '4a9972c08188'
down_revision = 'c4e2f5d8a1b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_authorized', sa.Boolean(), nullable=True),
    sa.Column('hire_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('termination_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_employee_id'), 'employees', ['employee_id'], unique=True)
    op.create_index(op.f('ix_employees_full_name'), 'employees', ['full_name'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_is_active'), 'employees', ['is_active'], unique=False)
    op.create_index(op.f('ix_employees_is_authorized'), 'employees', ['is_authorized'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=False)
    op.create_table('family_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('family_relationship', sa.String(length=30), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_authorized', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_members_full_name'), 'family_members', ['full_name'], unique=False)
    op.create_index(op.f('ix_family_members_id'), 'family_members', ['id'], unique=False)
    op.create_index(op.f('ix_family_members_is_active'), 'family_members', ['is_active'], unique=False)
    op.create_index(op.f('ix_family_members_is_authorized'), 'family_members', ['is_authorized'], unique=False)
    op.create_index(op.f('ix_family_members_user_id'), 'family_members', ['user_id'], unique=False)
    op.create_table('setup_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('region_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('license_plate_config', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manually_set', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setup_config_country_code'), 'setup_config', ['country_code'], unique=False)
    op.create_index(op.f('ix_setup_config_id'), 'setup_config', ['id'], unique=False)
    op.create_index(op.f('ix_setup_config_user_id'), 'setup_config', ['user_id'], unique=True)
    op.create_table('user_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=True),
    sa.Column('vehicle_type', sa.String(length=30), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_authorized', sa.Boolean(), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=True),
    sa.Column('blacklist_reason', sa.Text(), nullable=True),
    sa.Column('registration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_vehicles_category'), 'user_vehicles', ['category'], unique=False)
    op.create_index(op.f('ix_user_vehicles_id'), 'user_vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_user_vehicles_is_active'), 'user_vehicles', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_vehicles_is_authorized'), 'user_vehicles', ['is_authorized'], unique=False)
    op.create_index(op.f('ix_user_vehicles_is_blacklisted'), 'user_vehicles', ['is_blacklisted'], unique=False)
    op.create_index(op.f('ix_user_vehicles_license_plate'), 'user_vehicles', ['license_plate'], unique=True)
    op.create_index(op.f('ix_user_vehicles_owner_id'), 'user_vehicles', ['owner_id'], unique=False)
    op.create_index(op.f('ix_user_vehicles_vehicle_type'), 'user_vehicles', ['vehicle_type'], unique=False)
    op.create_index(op.f('ix_alert_rule_conditions_id'), 'alert_rule_conditions', ['id'], unique=False)
    op.add_column('users', sa.Column('setup_completed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('application_mode', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('country_code', sa.String(length=3), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_application_mode'), 'users', ['application_mode'], unique=False)
    op.create_index(op.f('ix_users_country_code'), 'users', ['country_code'], unique=False)
    op.create_index(op.f('ix_users_setup_completed'), 'users', ['setup_completed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_setup_completed'), table_name='users')
    op.drop_index(op.f('ix_users_country_code'), table_name='users')
    op.drop_index(op.f('ix_users_application_mode'), table_name='users')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'country_code')
    op.drop_column('users', 'application_mode')
    op.drop_column('users', 'setup_completed')
    op.drop_index(op.f('ix_alert_rule_conditions_id'), table_name='alert_rule_conditions')
    op.drop_index(op.f('ix_user_vehicles_vehicle_type'), table_name='user_vehicles')
    op.drop_index(op.f('ix_user_vehicles_owner_id'), table_name='user_vehicles')
    op.drop_index(op.f('ix_user_vehicles_license_plate'), table_name='user_vehicles')
    op.drop_index(op.f('ix_user_vehicles_is_blacklisted'), table_name='user_vehicles')
    op.drop_index(op.f('ix_user_vehicles_is_authorized'), table_name='user_vehicles')
    op.drop_index(op.f('ix_user_vehicles_is_active'), table_name='user_vehicles')
    op.drop_index(op.f('ix_user_vehicles_id'), table_name='user_vehicles')
    op.drop_index(op.f('ix_user_vehicles_category'), table_name='user_vehicles')
    op.drop_table('user_vehicles')
    op.drop_index(op.f('ix_setup_config_user_id'), table_name='setup_config')
    op.drop_index(op.f('ix_setup_config_id'), table_name='setup_config')
    op.drop_index(op.f('ix_setup_config_country_code'), table_name='setup_config')
    op.drop_table('setup_config')
    op.drop_index(op.f('ix_family_members_user_id'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_is_authorized'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_is_active'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_id'), table_name='family_members')
    op.drop_index(op.f('ix_family_members_full_name'), table_name='family_members')
    op.drop_table('family_members')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_is_authorized'), table_name='employees')
    op.drop_index(op.f('ix_employees_is_active'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_full_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_department'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
