"""Initial migration

Revision ID: a2762ca574b0
Revises: 
Create Date: 2026-04-10 00:20:22.222686
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'a2762ca574b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rtsp_url', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=15), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('zone_name', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('pan_tilt_zoom_capable', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_recording', sa.Boolean(), nullable=True),
    sa.Column('streaming_enabled', sa.Boolean(), nullable=True),
    sa.Column('connection_status', sa.String(length=20), nullable=False),
    sa.Column('last_connection_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connection_error', sa.String(length=500), nullable=True),
    sa.Column('motion_detection_enabled', sa.Boolean(), nullable=True),
    sa.Column('object_detection_enabled', sa.Boolean(), nullable=True),
    sa.Column('detection_sensitivity', sa.Integer(), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('camera_type', sa.String(length=20), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cameras_camera_type'), 'cameras', ['camera_type'], unique=False)
    op.create_index(op.f('ix_cameras_id'), 'cameras', ['id'], unique=False)
    op.create_index(op.f('ix_cameras_is_active'), 'cameras', ['is_active'], unique=False)
    op.create_index(op.f('ix_cameras_is_enabled'), 'cameras', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_cameras_owner_id'), 'cameras', ['owner_id'], unique=False)
    op.create_index(op.f('ix_cameras_site_id'), 'cameras', ['site_id'], unique=False)
    op.create_index(op.f('ix_cameras_tenant_id'), 'cameras', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cameras_zone_id'), 'cameras', ['zone_id'], unique=False)
    op.create_index(op.f('ix_cameras_zone_name'), 'cameras', ['zone_name'], unique=False)
    op.create_table('personnel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('cin', sa.String(length=20), nullable=False),
    sa.Column('cin_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('num_recrutement', sa.String(length=20), nullable=False),
    sa.Column('categorie', sa.Enum('OFFICIER', 'SOUS_OFFICIER', 'SOLDAT', 'SOLDAT_INVITE', 'CIVIL', name='personnelcategoryenum'), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('unite', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('face_embedding', sa.LargeBinary(), nullable=True),
    sa.Column('face_encodings', sa.JSON(), nullable=True),
    sa.Column('allowed_camera_ids', sa.JSON(), nullable=True),
    sa.Column('authorized_hours_start', sa.String(length=5), nullable=True),
    sa.Column('authorized_hours_end', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=True),
    sa.Column('blacklist_reason', sa.String(length=255), nullable=True),
    sa.Column('last_entry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_exit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_entries_today', sa.Integer(), nullable=True),
    sa.Column('date_enregistrement', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_personnel_categorie'), 'personnel', ['categorie'], unique=False)
    op.create_index(op.f('ix_personnel_cin'), 'personnel', ['cin'], unique=True)
    op.create_index(op.f('ix_personnel_full_name'), 'personnel', ['full_name'], unique=False)
    op.create_index(op.f('ix_personnel_grade'), 'personnel', ['grade'], unique=False)
    op.create_index(op.f('ix_personnel_id'), 'personnel', ['id'], unique=False)
    op.create_index(op.f('ix_personnel_is_active'), 'personnel', ['is_active'], unique=False)
    op.create_index(op.f('ix_personnel_is_blacklisted'), 'personnel', ['is_blacklisted'], unique=False)
    op.create_index(op.f('ix_personnel_nom'), 'personnel', ['nom'], unique=False)
    op.create_index(op.f('ix_personnel_num_recrutement'), 'personnel', ['num_recrutement'], unique=True)
    op.create_index(op.f('ix_personnel_prenom'), 'personnel', ['prenom'], unique=False)
    op.create_table('system_health_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_check', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_health_logs_created_at'), 'system_health_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_health_logs_id'), 'system_health_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_health_logs_last_check'), 'system_health_logs', ['last_check'], unique=False)
    op.create_index(op.f('ix_system_health_logs_service_name'), 'system_health_logs', ['service_name'], unique=False)
    op.create_index(op.f('ix_system_health_logs_status'), 'system_health_logs', ['status'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_created_at'), 'system_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=True),
    sa.Column('plan', sa.String(length=30), nullable=False),
    sa.Column('project_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_is_active'), 'tenants', ['is_active'], unique=False)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    op.create_index(op.f('ix_tenants_plan'), 'tenants', ['plan'], unique=False)
    op.create_index(op.f('ix_tenants_project_type'), 'tenants', ['project_type'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('vehicle_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricule', sa.String(length=20), nullable=False),
    sa.Column('marque', sa.String(length=50), nullable=False),
    sa.Column('modele', sa.String(length=50), nullable=False),
    sa.Column('couleur', sa.String(length=30), nullable=True),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('unite', sa.String(length=100), nullable=True),
    sa.Column('sous_categorie_militaire', sa.String(length=30), nullable=True),
    sa.Column('statut', sa.String(length=50), nullable=False),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('is_whitelisted', sa.Boolean(), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=True),
    sa.Column('blacklist_reason', sa.String(length=255), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('flag_reason', sa.String(length=255), nullable=True),
    sa.Column('date_enregistrement', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('date_modification', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_registry_categorie'), 'vehicle_registry', ['categorie'], unique=False)
    op.create_index(op.f('ix_vehicle_registry_date_enregistrement'), 'vehicle_registry', ['date_enregistrement'], unique=False)
    op.create_index(op.f('ix_vehicle_registry_id'), 'vehicle_registry', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_registry_is_blacklisted'), 'vehicle_registry', ['is_blacklisted'], unique=False)
    op.create_index(op.f('ix_vehicle_registry_is_flagged'), 'vehicle_registry', ['is_flagged'], unique=False)
    op.create_index(op.f('ix_vehicle_registry_is_whitelisted'), 'vehicle_registry', ['is_whitelisted'], unique=False)
    op.create_index(op.f('ix_vehicle_registry_matricule'), 'vehicle_registry', ['matricule'], unique=True)
    op.create_index(op.f('ix_vehicle_registry_sous_categorie_militaire'), 'vehicle_registry', ['sous_categorie_militaire'], unique=False)
    op.create_index(op.f('ix_vehicle_registry_statut'), 'vehicle_registry', ['statut'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('points', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('zone_type', sa.String(length=30), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('block_reason', sa.String(length=255), nullable=True),
    sa.Column('motion_detection_enabled', sa.Boolean(), nullable=True),
    sa.Column('object_detection_enabled', sa.Boolean(), nullable=True),
    sa.Column('sensitivity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_camera_id'), 'zones', ['camera_id'], unique=False)
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_index(op.f('ix_zones_is_blocked'), 'zones', ['is_blocked'], unique=False)
    op.create_index(op.f('ix_zones_site_id'), 'zones', ['site_id'], unique=False)
    op.create_index(op.f('ix_zones_tenant_id'), 'zones', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_zones_zone_type'), 'zones', ['zone_type'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('min_confidence', sa.Float(), nullable=True),
    sa.Column('min_object_count', sa.Integer(), nullable=True),
    sa.Column('enable_notification', sa.Boolean(), nullable=True),
    sa.Column('enable_recording', sa.Boolean(), nullable=True),
    sa.Column('enable_alert_sound', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_id'), 'alert_rules', ['id'], unique=False)
    op.create_index(op.f('ix_alert_rules_is_active'), 'alert_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_alert_rules_tenant_id'), 'alert_rules', ['tenant_id'], unique=False)
    op.create_table('face_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('face_encoding', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('match_quality', sa.String(length=20), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=255), nullable=True),
    sa.Column('face_bbox', sa.JSON(), nullable=True),
    sa.Column('person_bbox', sa.JSON(), nullable=True),
    sa.Column('appearance_top_color', sa.String(length=32), nullable=True),
    sa.Column('appearance_bottom_color', sa.String(length=32), nullable=True),
    sa.Column('has_backpack', sa.Boolean(), nullable=True),
    sa.Column('has_hat', sa.Boolean(), nullable=True),
    sa.Column('appearance_embedding', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_authorized', sa.Boolean(), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_detections_appearance_bottom_color'), 'face_detections', ['appearance_bottom_color'], unique=False)
    op.create_index(op.f('ix_face_detections_appearance_top_color'), 'face_detections', ['appearance_top_color'], unique=False)
    op.create_index(op.f('ix_face_detections_camera_id'), 'face_detections', ['camera_id'], unique=False)
    op.create_index(op.f('ix_face_detections_detected_at'), 'face_detections', ['detected_at'], unique=False)
    op.create_index(op.f('ix_face_detections_has_backpack'), 'face_detections', ['has_backpack'], unique=False)
    op.create_index(op.f('ix_face_detections_has_hat'), 'face_detections', ['has_hat'], unique=False)
    op.create_index(op.f('ix_face_detections_id'), 'face_detections', ['id'], unique=False)
    op.create_index(op.f('ix_face_detections_personnel_id'), 'face_detections', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_face_detections_track_id'), 'face_detections', ['track_id'], unique=False)
    op.create_index(op.f('ix_face_detections_zone_id'), 'face_detections', ['zone_id'], unique=False)
    op.create_table('face_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('pose_label', sa.String(length=20), nullable=True),
    sa.Column('yaw', sa.Float(), nullable=True),
    sa.Column('pitch', sa.Float(), nullable=True),
    sa.Column('roll', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('detector_score', sa.Float(), nullable=True),
    sa.Column('is_reference', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_images_id'), 'face_images', ['id'], unique=False)
    op.create_index(op.f('ix_face_images_is_reference'), 'face_images', ['is_reference'], unique=False)
    op.create_index(op.f('ix_face_images_personnel_id'), 'face_images', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_face_images_pose_label'), 'face_images', ['pose_label'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_code'), 'sites', ['code'], unique=True)
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_index(op.f('ix_sites_is_active'), 'sites', ['is_active'], unique=False)
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=True)
    op.create_index(op.f('ix_sites_tenant_id'), 'sites', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_last_login'), 'users', ['last_login'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vehicle_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_registry_id', sa.Integer(), nullable=True),
    sa.Column('license_plate', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('entry_camera_id', sa.Integer(), nullable=False),
    sa.Column('exit_camera_id', sa.Integer(), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_confidence', sa.Float(), nullable=True),
    sa.Column('exit_confidence', sa.Float(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entry_camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['exit_camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['vehicle_registry_id'], ['vehicle_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_entries_entry_time'), 'vehicle_entries', ['entry_time'], unique=False)
    op.create_index(op.f('ix_vehicle_entries_exit_time'), 'vehicle_entries', ['exit_time'], unique=False)
    op.create_index(op.f('ix_vehicle_entries_id'), 'vehicle_entries', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_entries_license_plate'), 'vehicle_entries', ['license_plate'], unique=False)
    op.create_index(op.f('ix_vehicle_entries_vehicle_registry_id'), 'vehicle_entries', ['vehicle_registry_id'], unique=False)
    op.create_table('vehicle_registry_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_registry_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('view_label', sa.String(length=20), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_reference', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_registry_id'], ['vehicle_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_registry_images_id'), 'vehicle_registry_images', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_registry_images_is_reference'), 'vehicle_registry_images', ['is_reference'], unique=False)
    op.create_index(op.f('ix_vehicle_registry_images_vehicle_registry_id'), 'vehicle_registry_images', ['vehicle_registry_id'], unique=False)
    op.create_index(op.f('ix_vehicle_registry_images_view_label'), 'vehicle_registry_images', ['view_label'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_path'), 'audit_logs', ['path'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_status_code'), 'audit_logs', ['status_code'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_username'), 'audit_logs', ['username'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detected_objects', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('snapshot_path', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_camera_id'), 'events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_events_decision'), 'events', ['decision'], unique=False)
    op.create_index(op.f('ix_events_detected_at'), 'events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_is_acknowledged'), 'events', ['is_acknowledged'], unique=False)
    op.create_index(op.f('ix_events_is_archived'), 'events', ['is_archived'], unique=False)
    op.create_index(op.f('ix_events_severity'), 'events', ['severity'], unique=False)
    op.create_index(op.f('ix_events_site_id'), 'events', ['site_id'], unique=False)
    op.create_index(op.f('ix_events_tenant_id'), 'events', ['tenant_id'], unique=False)
    op.create_table('face_encodings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('face_image_id', sa.Integer(), nullable=True),
    sa.Column('encoding_vector', sa.JSON(), nullable=False),
    sa.Column('embedding_vector', sa.JSON(), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('photo_hash', sa.String(length=64), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('detector_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['face_image_id'], ['face_images.id'], ),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_encodings_face_image_id'), 'face_encodings', ['face_image_id'], unique=False)
    op.create_index(op.f('ix_face_encodings_id'), 'face_encodings', ['id'], unique=False)
    op.create_index(op.f('ix_face_encodings_is_active'), 'face_encodings', ['is_active'], unique=False)
    op.create_index(op.f('ix_face_encodings_is_primary'), 'face_encodings', ['is_primary'], unique=False)
    op.create_index(op.f('ix_face_encodings_personnel_id'), 'face_encodings', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_face_encodings_photo_hash'), 'face_encodings', ['photo_hash'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_token_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_is_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('security_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('points', sa.JSON(), nullable=True),
    sa.Column('direction_mode', sa.String(length=20), nullable=False),
    sa.Column('schedule_mode', sa.String(length=20), nullable=False),
    sa.Column('active_from', sa.String(length=5), nullable=True),
    sa.Column('active_to', sa.String(length=5), nullable=True),
    sa.Column('sensitivity', sa.Integer(), nullable=True),
    sa.Column('object_type_filter', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_rules_camera_id'), 'security_rules', ['camera_id'], unique=False)
    op.create_index(op.f('ix_security_rules_direction_mode'), 'security_rules', ['direction_mode'], unique=False)
    op.create_index(op.f('ix_security_rules_id'), 'security_rules', ['id'], unique=False)
    op.create_index(op.f('ix_security_rules_is_active'), 'security_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_security_rules_name'), 'security_rules', ['name'], unique=False)
    op.create_index(op.f('ix_security_rules_object_type_filter'), 'security_rules', ['object_type_filter'], unique=False)
    op.create_index(op.f('ix_security_rules_rule_type'), 'security_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_security_rules_schedule_mode'), 'security_rules', ['schedule_mode'], unique=False)
    op.create_index(op.f('ix_security_rules_site_id'), 'security_rules', ['site_id'], unique=False)
    op.create_index(op.f('ix_security_rules_zone_id'), 'security_rules', ['zone_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('next_renewal_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renewal_period_days', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_auto_renew'), 'subscriptions', ['auto_renew'], unique=False)
    op.create_index(op.f('ix_subscriptions_expires_at'), 'subscriptions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_is_active'), 'subscriptions', ['is_active'], unique=False)
    op.create_index(op.f('ix_subscriptions_next_renewal_at'), 'subscriptions', ['next_renewal_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_tier'), 'subscriptions', ['tier'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('unknown_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detection_type', sa.String(length=20), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('source_table', sa.String(length=50), nullable=True),
    sa.Column('source_detection_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('is_ignored', sa.Boolean(), nullable=False),
    sa.Column('resolved_label', sa.String(length=120), nullable=True),
    sa.Column('resolved_entity_type', sa.String(length=30), nullable=True),
    sa.Column('resolved_entity_id', sa.Integer(), nullable=True),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unknown_detections_camera_id'), 'unknown_detections', ['camera_id'], unique=False)
    op.create_index(op.f('ix_unknown_detections_created_at'), 'unknown_detections', ['created_at'], unique=False)
    op.create_index(op.f('ix_unknown_detections_detection_type'), 'unknown_detections', ['detection_type'], unique=False)
    op.create_index(op.f('ix_unknown_detections_id'), 'unknown_detections', ['id'], unique=False)
    op.create_index(op.f('ix_unknown_detections_image_hash'), 'unknown_detections', ['image_hash'], unique=False)
    op.create_index(op.f('ix_unknown_detections_is_ignored'), 'unknown_detections', ['is_ignored'], unique=False)
    op.create_index(op.f('ix_unknown_detections_is_resolved'), 'unknown_detections', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_unknown_detections_resolved_at'), 'unknown_detections', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_unknown_detections_resolved_by_user_id'), 'unknown_detections', ['resolved_by_user_id'], unique=False)
    op.create_index(op.f('ix_unknown_detections_source_detection_id'), 'unknown_detections', ['source_detection_id'], unique=False)
    op.create_index(op.f('ix_unknown_detections_source_table'), 'unknown_detections', ['source_table'], unique=False)
    op.create_index(op.f('ix_unknown_detections_zone_id'), 'unknown_detections', ['zone_id'], unique=False)
    op.create_table('vehicle_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=50), nullable=True),
    sa.Column('plate_confidence', sa.Float(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('vehicle_entry_id', sa.Integer(), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=255), nullable=True),
    sa.Column('vehicle_bbox', sa.JSON(), nullable=True),
    sa.Column('plate_bbox', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['vehicle_entry_id'], ['vehicle_entries.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_detections_camera_id'), 'vehicle_detections', ['camera_id'], unique=False)
    op.create_index(op.f('ix_vehicle_detections_detected_at'), 'vehicle_detections', ['detected_at'], unique=False)
    op.create_index(op.f('ix_vehicle_detections_id'), 'vehicle_detections', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_detections_license_plate'), 'vehicle_detections', ['license_plate'], unique=False)
    op.create_index(op.f('ix_vehicle_detections_zone_id'), 'vehicle_detections', ['zone_id'], unique=False)
    op.create_table('vehicle_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=50), nullable=True),
    sa.Column('plate_type', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('vehicle_detected', sa.Boolean(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('body_style', sa.String(length=50), nullable=True),
    sa.Column('dominant_color', sa.String(length=30), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('vehicle_confidence', sa.Float(), nullable=True),
    sa.Column('vehicle_bbox', sa.JSON(), nullable=True),
    sa.Column('plate_confidence', sa.Float(), nullable=True),
    sa.Column('plate_bbox', sa.JSON(), nullable=True),
    sa.Column('raw_plate_text', sa.String(length=120), nullable=True),
    sa.Column('normalized_plate', sa.String(length=80), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_path', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('is_priority', sa.Boolean(), nullable=True),
    sa.Column('security_tag', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=120), nullable=True),
    sa.Column('matched_registry', sa.Boolean(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('consistency_level', sa.String(length=20), nullable=True),
    sa.Column('consistency_flags', sa.JSON(), nullable=True),
    sa.Column('anomaly_detected', sa.Boolean(), nullable=True),
    sa.Column('anomaly_level', sa.String(length=20), nullable=True),
    sa.Column('anomaly_reason', sa.String(length=160), nullable=True),
    sa.Column('anomaly_flags', sa.JSON(), nullable=True),
    sa.Column('pipeline_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_events_anomaly_detected'), 'vehicle_events', ['anomaly_detected'], unique=False)
    op.create_index(op.f('ix_vehicle_events_anomaly_level'), 'vehicle_events', ['anomaly_level'], unique=False)
    op.create_index(op.f('ix_vehicle_events_body_style'), 'vehicle_events', ['body_style'], unique=False)
    op.create_index(op.f('ix_vehicle_events_brand'), 'vehicle_events', ['brand'], unique=False)
    op.create_index(op.f('ix_vehicle_events_camera_id'), 'vehicle_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_vehicle_events_consistency_level'), 'vehicle_events', ['consistency_level'], unique=False)
    op.create_index(op.f('ix_vehicle_events_consistency_score'), 'vehicle_events', ['consistency_score'], unique=False)
    op.create_index(op.f('ix_vehicle_events_dominant_color'), 'vehicle_events', ['dominant_color'], unique=False)
    op.create_index(op.f('ix_vehicle_events_id'), 'vehicle_events', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_events_is_priority'), 'vehicle_events', ['is_priority'], unique=False)
    op.create_index(op.f('ix_vehicle_events_matched_registry'), 'vehicle_events', ['matched_registry'], unique=False)
    op.create_index(op.f('ix_vehicle_events_model'), 'vehicle_events', ['model'], unique=False)
    op.create_index(op.f('ix_vehicle_events_normalized_plate'), 'vehicle_events', ['normalized_plate'], unique=False)
    op.create_index(op.f('ix_vehicle_events_plate_number'), 'vehicle_events', ['plate_number'], unique=False)
    op.create_index(op.f('ix_vehicle_events_plate_type'), 'vehicle_events', ['plate_type'], unique=False)
    op.create_index(op.f('ix_vehicle_events_security_tag'), 'vehicle_events', ['security_tag'], unique=False)
    op.create_index(op.f('ix_vehicle_events_severity'), 'vehicle_events', ['severity'], unique=False)
    op.create_index(op.f('ix_vehicle_events_site_id'), 'vehicle_events', ['site_id'], unique=False)
    op.create_index(op.f('ix_vehicle_events_timestamp'), 'vehicle_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_vehicle_events_vehicle_detected'), 'vehicle_events', ['vehicle_detected'], unique=False)
    op.create_index(op.f('ix_vehicle_events_zone_id'), 'vehicle_events', ['zone_id'], unique=False)
    op.create_table('zone_occupancy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_entry_id', sa.Integer(), nullable=True),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.ForeignKeyConstraint(['vehicle_entry_id'], ['vehicle_entries.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_occupancy_id'), 'zone_occupancy', ['id'], unique=False)
    op.create_index(op.f('ix_zone_occupancy_is_active'), 'zone_occupancy', ['is_active'], unique=False)
    op.create_index(op.f('ix_zone_occupancy_personnel_id'), 'zone_occupancy', ['personnel_id'], unique=False)
    op.create_index(op.f('ix_zone_occupancy_vehicle_entry_id'), 'zone_occupancy', ['vehicle_entry_id'], unique=False)
    op.create_index(op.f('ix_zone_occupancy_zone_id'), 'zone_occupancy', ['zone_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('personnel_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personnel_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['personnel_id'], ['personnel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personnel_events_camera_id'), 'personnel_events', ['camera_id'], unique=False)
    op.create_index(op.f('ix_personnel_events_detected_at'), 'personnel_events', ['detected_at'], unique=False)
    op.create_index(op.f('ix_personnel_events_id'), 'personnel_events', ['id'], unique=False)
    op.create_index(op.f('ix_personnel_events_personnel_id'), 'personnel_events', ['personnel_id'], unique=False)
    op.create_table('subscription_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('previous_tier', sa.String(length=30), nullable=True),
    sa.Column('new_tier', sa.String(length=30), nullable=True),
    sa.Column('previous_status', sa.String(length=30), nullable=True),
    sa.Column('new_status', sa.String(length=30), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_history_action'), 'subscription_history', ['action'], unique=False)
    op.create_index(op.f('ix_subscription_history_created_by'), 'subscription_history', ['created_by'], unique=False)
    op.create_index(op.f('ix_subscription_history_id'), 'subscription_history', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_history_subscription_id'), 'subscription_history', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_subscription_history_user_id'), 'subscription_history', ['user_id'], unique=False)
    op.create_table('subscription_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_id', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_payments_id'), 'subscription_payments', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_paid_at'), 'subscription_payments', ['paid_at'], unique=False)
    op.create_index(op.f('ix_subscription_payments_reference_id'), 'subscription_payments', ['reference_id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_status'), 'subscription_payments', ['status'], unique=False)
    op.create_index(op.f('ix_subscription_payments_subscription_id'), 'subscription_payments', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_user_id'), 'subscription_payments', ['user_id'], unique=False)
    op.create_table('vehicle_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('plate_number', sa.String(length=50), nullable=True),
    sa.Column('normalized_plate', sa.String(length=80), nullable=True),
    sa.Column('plate_type', sa.String(length=20), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('gate_id', sa.String(length=60), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=12), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('vehicle_detected', sa.Boolean(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('plate_confidence', sa.Float(), nullable=True),
    sa.Column('security_tag', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=160), nullable=True),
    sa.Column('snapshot_path', sa.String(length=255), nullable=True),
    sa.Column('registry_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('operator_note', sa.Text(), nullable=True),
    sa.Column('dominant_color', sa.String(length=30), nullable=True),
    sa.Column('visual_consistency', sa.Float(), nullable=True),
    sa.Column('audit_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['vehicle_events.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['registry_vehicle_id'], ['vehicle_registry.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_access_logs_camera_id'), 'vehicle_access_logs', ['camera_id'], unique=False)
    op.create_index(op.f('ix_vehicle_access_logs_created_at'), 'vehicle_access_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_vehicle_access_logs_decision'), 'vehicle_access_logs', ['decision'], unique=False)
    op.create_index(op.f('ix_vehicle_access_logs_direction'), 'vehicle_access_logs', ['direction'], unique=False)
    op.create_index(op.f('ix_vehicle_access_logs_event_id'), 'vehicle_access_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_vehicle_access_logs_gate_id'), 'vehicle_access_logs', ['gate_id'], unique=False)
    op.create_index(op.f('ix_vehicle_access_logs_id'), 'vehicle_access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_access_logs_normalized_plate'), 'vehicle_access_logs', ['normalized_plate'], unique=False)
    op.create_index(op.f('ix_vehicle_access_logs_operator_id'), 'vehicle_access_logs', ['operator_id'], unique=False)
    op.create_index(op.f('ix_vehicle_access_logs_plate_number'), 'vehicle_access_logs', ['plate_number'], unique=False)
    op.create_index(op.f('ix_vehicle_access_logs_plate_type'), 'vehicle_access_logs', ['plate_type'], unique=False)
    op.create_index(op.f('ix_vehicle_access_logs_registry_vehicle_id'), 'vehicle_access_logs', ['registry_vehicle_id'], unique=False)
    op.create_index(op.f('ix_vehicle_access_logs_security_tag'), 'vehicle_access_logs', ['security_tag'], unique=False)
    op.create_index(op.f('ix_vehicle_access_logs_site_id'), 'vehicle_access_logs', ['site_id'], unique=False)
    op.create_index(op.f('ix_vehicle_access_logs_timestamp'), 'vehicle_access_logs', ['timestamp'], unique=False)
    op.create_table('vehicle_event_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('frame_path', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('ocr_text', sa.String(length=120), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('frame_meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['vehicle_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_event_frames_created_at'), 'vehicle_event_frames', ['created_at'], unique=False)
    op.create_index(op.f('ix_vehicle_event_frames_event_id'), 'vehicle_event_frames', ['event_id'], unique=False)
    op.create_index(op.f('ix_vehicle_event_frames_id'), 'vehicle_event_frames', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_event_frames_stage'), 'vehicle_event_frames', ['stage'], unique=False)
    op.create_index(op.f('ix_vehicle_event_frames_timestamp'), 'vehicle_event_frames', ['timestamp'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=50), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('direction', sa.String(length=50), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_camera_id'), 'vehicles', ['camera_id'], unique=False)
    op.create_index(op.f('ix_vehicles_id'), 'vehicles', ['id'], unique=False)
    op.create_index(op.f('ix_vehicles_license_plate'), 'vehicles', ['license_plate'], unique=False)
    op.create_table('security_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('plate_number', sa.String(length=50), nullable=True),
    sa.Column('normalized_plate', sa.String(length=80), nullable=True),
    sa.Column('camera_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('gate_id', sa.String(length=60), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity_level', sa.String(length=20), nullable=False),
    sa.Column('resolution_status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('access_log_id', sa.Integer(), nullable=True),
    sa.Column('handled_by', sa.Integer(), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_path', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['access_log_id'], ['vehicle_access_logs.id'], ),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['vehicle_events.id'], ),
    sa.ForeignKeyConstraint(['handled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_alerts_access_log_id'), 'security_alerts', ['access_log_id'], unique=False)
    op.create_index(op.f('ix_security_alerts_camera_id'), 'security_alerts', ['camera_id'], unique=False)
    op.create_index(op.f('ix_security_alerts_created_at'), 'security_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_security_alerts_event_id'), 'security_alerts', ['event_id'], unique=False)
    op.create_index(op.f('ix_security_alerts_gate_id'), 'security_alerts', ['gate_id'], unique=False)
    op.create_index(op.f('ix_security_alerts_handled_by'), 'security_alerts', ['handled_by'], unique=False)
    op.create_index(op.f('ix_security_alerts_id'), 'security_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_security_alerts_normalized_plate'), 'security_alerts', ['normalized_plate'], unique=False)
    op.create_index(op.f('ix_security_alerts_plate_number'), 'security_alerts', ['plate_number'], unique=False)
    op.create_index(op.f('ix_security_alerts_resolution_status'), 'security_alerts', ['resolution_status'], unique=False)
    op.create_index(op.f('ix_security_alerts_severity_level'), 'security_alerts', ['severity_level'], unique=False)
    op.create_index(op.f('ix_security_alerts_site_id'), 'security_alerts', ['site_id'], unique=False)
    op.create_index(op.f('ix_security_alerts_tenant_id'), 'security_alerts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_security_alerts_timestamp'), 'security_alerts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_security_alerts_type'), 'security_alerts', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_alerts_type'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_timestamp'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_tenant_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_site_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_severity_level'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_resolution_status'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_plate_number'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_normalized_plate'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_handled_by'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_gate_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_event_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_created_at'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_camera_id'), table_name='security_alerts')
    op.drop_index(op.f('ix_security_alerts_access_log_id'), table_name='security_alerts')
    op.drop_table('security_alerts')
    op.drop_index(op.f('ix_vehicles_license_plate'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_camera_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_vehicle_event_frames_timestamp'), table_name='vehicle_event_frames')
    op.drop_index(op.f('ix_vehicle_event_frames_stage'), table_name='vehicle_event_frames')
    op.drop_index(op.f('ix_vehicle_event_frames_id'), table_name='vehicle_event_frames')
    op.drop_index(op.f('ix_vehicle_event_frames_event_id'), table_name='vehicle_event_frames')
    op.drop_index(op.f('ix_vehicle_event_frames_created_at'), table_name='vehicle_event_frames')
    op.drop_table('vehicle_event_frames')
    op.drop_index(op.f('ix_vehicle_access_logs_timestamp'), table_name='vehicle_access_logs')
    op.drop_index(op.f('ix_vehicle_access_logs_site_id'), table_name='vehicle_access_logs')
    op.drop_index(op.f('ix_vehicle_access_logs_security_tag'), table_name='vehicle_access_logs')
    op.drop_index(op.f('ix_vehicle_access_logs_registry_vehicle_id'), table_name='vehicle_access_logs')
    op.drop_index(op.f('ix_vehicle_access_logs_plate_type'), table_name='vehicle_access_logs')
    op.drop_index(op.f('ix_vehicle_access_logs_plate_number'), table_name='vehicle_access_logs')
    op.drop_index(op.f('ix_vehicle_access_logs_operator_id'), table_name='vehicle_access_logs')
    op.drop_index(op.f('ix_vehicle_access_logs_normalized_plate'), table_name='vehicle_access_logs')
    op.drop_index(op.f('ix_vehicle_access_logs_id'), table_name='vehicle_access_logs')
    op.drop_index(op.f('ix_vehicle_access_logs_gate_id'), table_name='vehicle_access_logs')
    op.drop_index(op.f('ix_vehicle_access_logs_event_id'), table_name='vehicle_access_logs')
    op.drop_index(op.f('ix_vehicle_access_logs_direction'), table_name='vehicle_access_logs')
    op.drop_index(op.f('ix_vehicle_access_logs_decision'), table_name='vehicle_access_logs')
    op.drop_index(op.f('ix_vehicle_access_logs_created_at'), table_name='vehicle_access_logs')
    op.drop_index(op.f('ix_vehicle_access_logs_camera_id'), table_name='vehicle_access_logs')
    op.drop_table('vehicle_access_logs')
    op.drop_index(op.f('ix_subscription_payments_user_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_subscription_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_status'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_reference_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_paid_at'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_id'), table_name='subscription_payments')
    op.drop_table('subscription_payments')
    op.drop_index(op.f('ix_subscription_history_user_id'), table_name='subscription_history')
    op.drop_index(op.f('ix_subscription_history_subscription_id'), table_name='subscription_history')
    op.drop_index(op.f('ix_subscription_history_id'), table_name='subscription_history')
    op.drop_index(op.f('ix_subscription_history_created_by'), table_name='subscription_history')
    op.drop_index(op.f('ix_subscription_history_action'), table_name='subscription_history')
    op.drop_table('subscription_history')
    op.drop_index(op.f('ix_personnel_events_personnel_id'), table_name='personnel_events')
    op.drop_index(op.f('ix_personnel_events_id'), table_name='personnel_events')
    op.drop_index(op.f('ix_personnel_events_detected_at'), table_name='personnel_events')
    op.drop_index(op.f('ix_personnel_events_camera_id'), table_name='personnel_events')
    op.drop_table('personnel_events')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_zone_occupancy_zone_id'), table_name='zone_occupancy')
    op.drop_index(op.f('ix_zone_occupancy_vehicle_entry_id'), table_name='zone_occupancy')
    op.drop_index(op.f('ix_zone_occupancy_personnel_id'), table_name='zone_occupancy')
    op.drop_index(op.f('ix_zone_occupancy_is_active'), table_name='zone_occupancy')
    op.drop_index(op.f('ix_zone_occupancy_id'), table_name='zone_occupancy')
    op.drop_table('zone_occupancy')
    op.drop_index(op.f('ix_vehicle_events_zone_id'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_vehicle_detected'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_timestamp'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_site_id'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_severity'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_security_tag'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_plate_type'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_plate_number'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_normalized_plate'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_model'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_matched_registry'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_is_priority'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_id'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_dominant_color'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_consistency_score'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_consistency_level'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_camera_id'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_brand'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_body_style'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_anomaly_level'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_anomaly_detected'), table_name='vehicle_events')
    op.drop_table('vehicle_events')
    op.drop_index(op.f('ix_vehicle_detections_zone_id'), table_name='vehicle_detections')
    op.drop_index(op.f('ix_vehicle_detections_license_plate'), table_name='vehicle_detections')
    op.drop_index(op.f('ix_vehicle_detections_id'), table_name='vehicle_detections')
    op.drop_index(op.f('ix_vehicle_detections_detected_at'), table_name='vehicle_detections')
    op.drop_index(op.f('ix_vehicle_detections_camera_id'), table_name='vehicle_detections')
    op.drop_table('vehicle_detections')
    op.drop_index(op.f('ix_unknown_detections_zone_id'), table_name='unknown_detections')
    op.drop_index(op.f('ix_unknown_detections_source_table'), table_name='unknown_detections')
    op.drop_index(op.f('ix_unknown_detections_source_detection_id'), table_name='unknown_detections')
    op.drop_index(op.f('ix_unknown_detections_resolved_by_user_id'), table_name='unknown_detections')
    op.drop_index(op.f('ix_unknown_detections_resolved_at'), table_name='unknown_detections')
    op.drop_index(op.f('ix_unknown_detections_is_resolved'), table_name='unknown_detections')
    op.drop_index(op.f('ix_unknown_detections_is_ignored'), table_name='unknown_detections')
    op.drop_index(op.f('ix_unknown_detections_image_hash'), table_name='unknown_detections')
    op.drop_index(op.f('ix_unknown_detections_id'), table_name='unknown_detections')
    op.drop_index(op.f('ix_unknown_detections_detection_type'), table_name='unknown_detections')
    op.drop_index(op.f('ix_unknown_detections_created_at'), table_name='unknown_detections')
    op.drop_index(op.f('ix_unknown_detections_camera_id'), table_name='unknown_detections')
    op.drop_table('unknown_detections')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tier'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_next_renewal_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_is_active'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_expires_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_auto_renew'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_security_rules_zone_id'), table_name='security_rules')
    op.drop_index(op.f('ix_security_rules_site_id'), table_name='security_rules')
    op.drop_index(op.f('ix_security_rules_schedule_mode'), table_name='security_rules')
    op.drop_index(op.f('ix_security_rules_rule_type'), table_name='security_rules')
    op.drop_index(op.f('ix_security_rules_object_type_filter'), table_name='security_rules')
    op.drop_index(op.f('ix_security_rules_name'), table_name='security_rules')
    op.drop_index(op.f('ix_security_rules_is_active'), table_name='security_rules')
    op.drop_index(op.f('ix_security_rules_id'), table_name='security_rules')
    op.drop_index(op.f('ix_security_rules_direction_mode'), table_name='security_rules')
    op.drop_index(op.f('ix_security_rules_camera_id'), table_name='security_rules')
    op.drop_table('security_rules')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_face_encodings_photo_hash'), table_name='face_encodings')
    op.drop_index(op.f('ix_face_encodings_personnel_id'), table_name='face_encodings')
    op.drop_index(op.f('ix_face_encodings_is_primary'), table_name='face_encodings')
    op.drop_index(op.f('ix_face_encodings_is_active'), table_name='face_encodings')
    op.drop_index(op.f('ix_face_encodings_id'), table_name='face_encodings')
    op.drop_index(op.f('ix_face_encodings_face_image_id'), table_name='face_encodings')
    op.drop_table('face_encodings')
    op.drop_index(op.f('ix_events_tenant_id'), table_name='events')
    op.drop_index(op.f('ix_events_site_id'), table_name='events')
    op.drop_index(op.f('ix_events_severity'), table_name='events')
    op.drop_index(op.f('ix_events_is_archived'), table_name='events')
    op.drop_index(op.f('ix_events_is_acknowledged'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_detected_at'), table_name='events')
    op.drop_index(op.f('ix_events_decision'), table_name='events')
    op.drop_index(op.f('ix_events_camera_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_audit_logs_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status_code'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_path'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_vehicle_registry_images_view_label'), table_name='vehicle_registry_images')
    op.drop_index(op.f('ix_vehicle_registry_images_vehicle_registry_id'), table_name='vehicle_registry_images')
    op.drop_index(op.f('ix_vehicle_registry_images_is_reference'), table_name='vehicle_registry_images')
    op.drop_index(op.f('ix_vehicle_registry_images_id'), table_name='vehicle_registry_images')
    op.drop_table('vehicle_registry_images')
    op.drop_index(op.f('ix_vehicle_entries_vehicle_registry_id'), table_name='vehicle_entries')
    op.drop_index(op.f('ix_vehicle_entries_license_plate'), table_name='vehicle_entries')
    op.drop_index(op.f('ix_vehicle_entries_id'), table_name='vehicle_entries')
    op.drop_index(op.f('ix_vehicle_entries_exit_time'), table_name='vehicle_entries')
    op.drop_index(op.f('ix_vehicle_entries_entry_time'), table_name='vehicle_entries')
    op.drop_table('vehicle_entries')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_last_login'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sites_tenant_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_index(op.f('ix_sites_is_active'), table_name='sites')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_code'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_face_images_pose_label'), table_name='face_images')
    op.drop_index(op.f('ix_face_images_personnel_id'), table_name='face_images')
    op.drop_index(op.f('ix_face_images_is_reference'), table_name='face_images')
    op.drop_index(op.f('ix_face_images_id'), table_name='face_images')
    op.drop_table('face_images')
    op.drop_index(op.f('ix_face_detections_zone_id'), table_name='face_detections')
    op.drop_index(op.f('ix_face_detections_track_id'), table_name='face_detections')
    op.drop_index(op.f('ix_face_detections_personnel_id'), table_name='face_detections')
    op.drop_index(op.f('ix_face_detections_id'), table_name='face_detections')
    op.drop_index(op.f('ix_face_detections_has_hat'), table_name='face_detections')
    op.drop_index(op.f('ix_face_detections_has_backpack'), table_name='face_detections')
    op.drop_index(op.f('ix_face_detections_detected_at'), table_name='face_detections')
    op.drop_index(op.f('ix_face_detections_camera_id'), table_name='face_detections')
    op.drop_index(op.f('ix_face_detections_appearance_top_color'), table_name='face_detections')
    op.drop_index(op.f('ix_face_detections_appearance_bottom_color'), table_name='face_detections')
    op.drop_table('face_detections')
    op.drop_index(op.f('ix_alert_rules_tenant_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_is_active'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_zones_zone_type'), table_name='zones')
    op.drop_index(op.f('ix_zones_tenant_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_site_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_is_blocked'), table_name='zones')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_camera_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_vehicle_registry_statut'), table_name='vehicle_registry')
    op.drop_index(op.f('ix_vehicle_registry_sous_categorie_militaire'), table_name='vehicle_registry')
    op.drop_index(op.f('ix_vehicle_registry_matricule'), table_name='vehicle_registry')
    op.drop_index(op.f('ix_vehicle_registry_is_whitelisted'), table_name='vehicle_registry')
    op.drop_index(op.f('ix_vehicle_registry_is_flagged'), table_name='vehicle_registry')
    op.drop_index(op.f('ix_vehicle_registry_is_blacklisted'), table_name='vehicle_registry')
    op.drop_index(op.f('ix_vehicle_registry_id'), table_name='vehicle_registry')
    op.drop_index(op.f('ix_vehicle_registry_date_enregistrement'), table_name='vehicle_registry')
    op.drop_index(op.f('ix_vehicle_registry_categorie'), table_name='vehicle_registry')
    op.drop_table('vehicle_registry')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_project_type'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_plan'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_is_active'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_created_at'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_system_health_logs_status'), table_name='system_health_logs')
    op.drop_index(op.f('ix_system_health_logs_service_name'), table_name='system_health_logs')
    op.drop_index(op.f('ix_system_health_logs_last_check'), table_name='system_health_logs')
    op.drop_index(op.f('ix_system_health_logs_id'), table_name='system_health_logs')
    op.drop_index(op.f('ix_system_health_logs_created_at'), table_name='system_health_logs')
    op.drop_table('system_health_logs')
    op.drop_index(op.f('ix_personnel_prenom'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_num_recrutement'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_nom'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_is_blacklisted'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_is_active'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_id'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_grade'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_full_name'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_cin'), table_name='personnel')
    op.drop_index(op.f('ix_personnel_categorie'), table_name='personnel')
    op.drop_table('personnel')
    op.drop_index(op.f('ix_cameras_zone_name'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_zone_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_tenant_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_site_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_owner_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_is_enabled'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_is_active'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_id'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_camera_type'), table_name='cameras')
    op.drop_table('cameras')
    # ### end Alembic commands ###
